menu:
  Blog: /
  Archive: /archives/
  About: /about/
  GitHub: https://github.com/joemacaco

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: joemacaco
duoshuo:
cloudTie:

# Analytics
# google-analytics:
ga: UA-78758976-1

# Copyright Infomation
startyear: 2016
